# Generated by Django 4.0.6 on 2022-07-24 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_estudiante_delete_registrado'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estudiante',
            new_name='Estudiantes',
        ),
    ]
