# Generated by Django 4.0.6 on 2022-07-24 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_rename_estudiante_estudiantes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('materia', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
