# Generated by Django 4.0.6 on 2022-07-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_profesores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMateria', models.CharField(blank=True, max_length=50, null=True)),
                ('nivel', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
